2ff: Make it idempotent and clean it up a bit
If a file begins with "farbfeld", we just pass it through.

diff --git a/2ff b/2ff
--- a/2ff
+++ b/2ff
@@ -5,20 +5,32 @@ if [ "$#" -ne 0 ]; then
 fi
 
 TMP=$(mktemp)
-cat > "$TMP";
+cat > "$TMP"
 
-FORMAT=$(file -ib "$TMP" | cut -d ";" -f 1);
-
-case "$FORMAT" in
-    image/png)  png2ff < "$TMP"; ret=$? ;;
-    image/jpeg) jpg2ff < "$TMP"; ret=$? ;;
-    *) convert "$TMP" png:- 2>/dev/null | png2ff 2>/dev/null; ret=$? ;;
-esac
-
-rm "$TMP";
-
-if [ $ret -ne 0 ]; then
-	printf "%s: failed to convert %s\n" "$0" "$FORMAT" >&2;
+if [ "$(head -c 8 "$TMP")" = "farbfeld" ]; then
+	cat < "$TMP"
+	exit 0
 fi
 
-exit $ret;
+FORMAT=$(file -ib "$TMP" | cut -d ";" -f 1)
+
+case "$FORMAT" in
+image/png)
+	png2ff < "$TMP"
+	;;
+image/jpeg)
+	jpg2ff < "$TMP"
+	;;
+*)
+	convert "$TMP" png:- 2>/dev/null | png2ff 2>/dev/null
+	;;
+esac
+
+ret=$?
+rm "$TMP"
+
+if [ $ret -ne 0 ]; then
+	printf "%s: failed to convert from %s\n" "$0" "$FORMAT" >&2
+fi
+
+exit $ret
