Fix 2ff stderr-redirect
Thanks izabera for spotting this!

diff --git a/2ff b/2ff
--- a/2ff
+++ b/2ff
@@ -12,13 +12,13 @@ FORMAT=$(file -ib $TMP | cut -d ";" -f 1);
 case "$FORMAT" in
     image/png)  png2ff < $TMP; ret=$? ;;
     image/jpeg) jpg2ff < $TMP; ret=$? ;;
-    *) xconvert $TMP png:- 2&>/dev/null | png2ff 2&>/dev/null; ret=$? ;;
+    *) xconvert $TMP png:- 2>/dev/null | png2ff 2>/dev/null; ret=$? ;;
 esac
 
 rm $TMP;
 
 if [ $ret -ne 0 ]; then
-	printf "%s: failed to convert %s\n" "$0" "$FORMAT" 1>&2;
+	printf "%s: failed to convert %s\n" "$0" "$FORMAT" >&2;
 fi
 
 exit $ret;
